-- MySQL Script generated by MySQL Workbench
-- Sun Mar 30 23:36:00 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema proyecto_atai_corregido
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema proyecto_atai_corregido
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `proyecto_atai_corregido` DEFAULT CHARACTER SET utf8 ;
USE `proyecto_atai_corregido` ;

-- -----------------------------------------------------
-- Table `proyecto_atai_corregido`.`miembros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_atai_corregido`.`miembros` (
  `idMIEMBROS` INT NOT NULL,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `apellido` VARCHAR(45) NULL DEFAULT NULL,
  `dni` VARCHAR(45) NULL DEFAULT NULL,
  `telefono` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`idMIEMBROS`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `proyecto_atai_corregido`.`aprendices`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_atai_corregido`.`aprendices` (
  `nivel` VARCHAR(45) NULL DEFAULT NULL,
  `objetivo` VARCHAR(45) NULL DEFAULT NULL,
  `fecha_finalizacion` VARCHAR(45) NULL DEFAULT NULL,
  `id_miembro` INT NOT NULL,
  PRIMARY KEY (`id_miembro`),
  INDEX `fk_APRENDICES_MIEMBROS1_idx` (`id_miembro` ASC) VISIBLE,
  CONSTRAINT `fk_APRENDICES_MIEMBROS1`
    FOREIGN KEY (`id_miembro`)
    REFERENCES `proyecto_atai_corregido`.`miembros` (`idMIEMBROS`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `proyecto_atai_corregido`.`ubicacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_atai_corregido`.`ubicacion` (
  `id_ubicacion` INT NOT NULL,
  `capacidad` INT NULL DEFAULT NULL,
  `estado` VARCHAR(45) NULL DEFAULT NULL,
  `tipo_sala` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_ubicacion`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `proyecto_atai_corregido`.`clases`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_atai_corregido`.`clases` (
  `id_clases` INT NOT NULL,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `duracion` TIME NULL DEFAULT NULL,
  `horario` VARCHAR(45) NULL DEFAULT NULL,
  `capacidad` VARCHAR(45) NULL DEFAULT NULL,
  `UBICACION_id_ubicacion` INT NOT NULL,
  PRIMARY KEY (`id_clases`),
  INDEX `fk_CLASES_UBICACION1_idx` (`UBICACION_id_ubicacion` ASC) VISIBLE,
  CONSTRAINT `fk_CLASES_UBICACION1`
    FOREIGN KEY (`UBICACION_id_ubicacion`)
    REFERENCES `proyecto_atai_corregido`.`ubicacion` (`id_ubicacion`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `proyecto_atai_corregido`.`entrenadores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_atai_corregido`.`entrenadores` (
  `tipo_entrenador` VARCHAR(45) NULL DEFAULT NULL,
  `disponibilidad` VARCHAR(45) CHARACTER SET 'utf8mb3' NULL DEFAULT NULL,
  `rango` VARCHAR(45) NULL DEFAULT NULL,
  `id_miembro` INT NOT NULL,
  `CLASES_id_clases` INT NOT NULL,
  PRIMARY KEY (`id_miembro`),
  INDEX `fk_ENTRENADORES_MIEMBROS_idx` (`id_miembro` ASC) VISIBLE,
  INDEX `fk_ENTRENADORES_CLASES1_idx` (`CLASES_id_clases` ASC) VISIBLE,
  CONSTRAINT `fk_ENTRENADORES_CLASES1`
    FOREIGN KEY (`CLASES_id_clases`)
    REFERENCES `proyecto_atai_corregido`.`clases` (`id_clases`),
  CONSTRAINT `fk_ENTRENADORES_MIEMBROS`
    FOREIGN KEY (`id_miembro`)
    REFERENCES `proyecto_atai_corregido`.`miembros` (`idMIEMBROS`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `proyecto_atai_corregido`.`tarifas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_atai_corregido`.`tarifas` (
  `id_tarifa` INT NOT NULL,
  `calidad` VARCHAR(45) NULL DEFAULT NULL,
  `precio` VARCHAR(45) NULL DEFAULT NULL,
  `estado` VARCHAR(45) NULL DEFAULT NULL,
  `tipo` ENUM('Anual', 'Trimestral') NULL DEFAULT NULL,
  PRIMARY KEY (`id_tarifa`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `proyecto_atai_corregido`.`matricula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_atai_corregido`.`matricula` (
  `id_matricula` INT NOT NULL,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `duracion` VARCHAR(45) NULL DEFAULT NULL,
  `APRENDICES_id_miembro` INT NOT NULL,
  `TARIFAS_id_tarifa` INT NOT NULL,
  PRIMARY KEY (`id_matricula`),
  INDEX `fk_MATRICULA_APRENDICES1_idx` (`APRENDICES_id_miembro` ASC) VISIBLE,
  INDEX `fk_MATRICULA_TARIFAS1_idx` (`TARIFAS_id_tarifa` ASC) VISIBLE,
  CONSTRAINT `fk_MATRICULA_APRENDICES1`
    FOREIGN KEY (`APRENDICES_id_miembro`)
    REFERENCES `proyecto_atai_corregido`.`aprendices` (`id_miembro`),
  CONSTRAINT `fk_MATRICULA_TARIFAS1`
    FOREIGN KEY (`TARIFAS_id_tarifa`)
    REFERENCES `proyecto_atai_corregido`.`tarifas` (`id_tarifa`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `proyecto_atai_corregido`.`pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_atai_corregido`.`pago` (
  `numero_tarjeta` VARCHAR(19) NOT NULL,
  `fecha_vencimiento` VARCHAR(45) NULL DEFAULT NULL,
  `estado_tarjeta` ENUM('Activa', 'Suspendida', 'Expirada', 'Bloqueada') NULL DEFAULT NULL,
  `MATRICULA_id_matricula` INT NOT NULL,
  PRIMARY KEY (`numero_tarjeta`, `MATRICULA_id_matricula`),
  INDEX `fk_PAGO_MATRICULA1_idx` (`MATRICULA_id_matricula` ASC) VISIBLE,
  CONSTRAINT `fk_PAGO_MATRICULA1`
    FOREIGN KEY (`MATRICULA_id_matricula`)
    REFERENCES `proyecto_atai_corregido`.`matricula` (`id_matricula`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `proyecto_atai_corregido`.`realizan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_atai_corregido`.`realizan` (
  `APRENDICES_id_miembro` INT NOT NULL,
  `CLASES_id_clases` INT NOT NULL,
  PRIMARY KEY (`APRENDICES_id_miembro`, `CLASES_id_clases`),
  INDEX `fk_APRENDICES_has_CLASES_CLASES1_idx` (`CLASES_id_clases` ASC) VISIBLE,
  INDEX `fk_APRENDICES_has_CLASES_APRENDICES1_idx` (`APRENDICES_id_miembro` ASC) VISIBLE,
  CONSTRAINT `fk_APRENDICES_has_CLASES_APRENDICES1`
    FOREIGN KEY (`APRENDICES_id_miembro`)
    REFERENCES `proyecto_atai_corregido`.`aprendices` (`id_miembro`),
  CONSTRAINT `fk_APRENDICES_has_CLASES_CLASES1`
    FOREIGN KEY (`CLASES_id_clases`)
    REFERENCES `proyecto_atai_corregido`.`clases` (`id_clases`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
